name: "Continuous deployment"
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    - uses: cachix/cachix-action@v8
      with:
        name: flibrary
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: "45.32.131.167 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH644x5o56908R+LCQPpTOiBm7Oqp1ELk4rT3Jj1jkTD"
        name: id_ed25519
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - run: nix run .#deploy
